
### Immunization - Search by Patient with/without date administered
GET http://localhost:3000/api/satusehat/Immunization?date=2022-01-11&patient=100000030009

### Immunization - Search by ID
GET http://localhost:3000/api/satusehat/Immunization/:id

### Immunization - UPDATE
PUT http://localhost:3000/api/satusehat/Immunization/:id
Content-type: application/json

{
    "resourceType": "Immunization",
    "id": "cbda5884-f180-4118-911e-9bd35e09651a",
    "status": "not-done",
    "vaccineCode": {
        "coding": [
            {
                "system": "http://sys-ids.kemkes.go.id/kfa",
                "code": "93001282",
                "display": "Vaksin DTP - HB - Hib 0,5 mL (PENTABIO, 1)"
            },
            {
                "system": "http://sys-ids.kemkes.go.id/kfa",
                "code": "VG17",
                "display": "HIB"
            },
            {
                "system": "http://hl7.org/fhir/sid/cvx",
                "code": "102",
                "display": "DTP-Hib-Hep B"
            }
        ]
    },
    "patient": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "encounter": {
        "reference": "Encounter/8a224d91-5132-47d0-ae35-0fc70f24a776"
    },
    "occurrenceDateTime": "2022-01-10",
    "recorded": "2022-01-10",
    "primarySource": true,
    "location": {
        "reference": "Location/ef011065-38c9-46f8-9c35-d1fe68966a3e",
        "display": "Ruang 1A, Poliklinik Rawat Jalan"
    },
    "lotNumber": "202009007",
    "route": {
        "coding": [
            {
                "system": "http://www.whocc.no/atc",
                "code": "inj.intramuscular",
                "display": "Injection Intramuscular"
            }
        ]
    },
    "doseQuantity": {
        "value": 1,
        "unit": "mL",
        "system": "http://unitsofmeasure.org",
        "code": "ml"
    },
    "performer": [
        {
            "function": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0443",
                        "code": "AP",
                        "display": "Administering Provider"
                    }
                ]
            },
            "actor": {
                "reference": "Practitioner/N10000001"
            }
        }
    ],
    "reasonCode": [
        {
            "coding": [
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/immunization-reason",
                    "code": "IM-Dasar",
                    "display": "Imunisasi Program Rutin Dasar"
                },
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/immunization-routine-timing",
                    "code": "IM-Ideal",
                    "display": "Imunisasi Ideal"
                }
            ]
        }
    ],
    "protocolApplied": [
        {
            "doseNumberPositiveInt": 1
        }
    ]
}

### Immunization - PATCH
PATCH http://localhost:3000/api/satusehat/Immunization/:id
Content-Type: application/json-patch+json

[
    {
        "op": "replace",
        "path": "/status",
        "value": "entered-in-error"
    }
]

