@Encounter_uuid=

### AllergyIntolerance - Create
POST http://localhost:3000/api/satusehat/AllergyIntolerance
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "AllergyIntolerance",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/allergy/{{Org_id}}",
            "use": "official",
            "value": "98457729"
        }
    ],
    "clinicalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                "code": "active",
                "display": "Active"
            }
        ]
    },
    "verificationStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                "code": "confirmed",
                "display": "Confirmed"
            }
        ]
    },
    "category": [
        "food"
    ],
    "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "89811004",
                "display": "Gluten"
            }
        ],
        "text": "Alergi bahan gluten, khususnya ketika makan roti gandum"
    },
    "patient": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022"
    },
    "recordedDate": "2022-06-14T15:37:31+07:00",
    "recorder": {
        "reference": "Practitioner/N10000001"
    }
}

### AllergyIntolerance - Search by Subject with/without Allergy Code
GET http://localhost:3000/api/satusehat/AllergyIntolerance?patient=100000030009&code=89811004
Authorization: Bearer {{token}}

### AllergyIntolerance - Search by ID
GET http://localhost:3000/api/satusehat/AllergyIntolerance/:id
Authorization: Bearer {{token}}

### AllergyIntolerance - Update
PUT http://localhost:3000/api/satusehat/AllergyIntolerance/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "AllergyIntolerance",
    "id": "94b05c94-7429-4e98-bebe-d9cbda19d3d5",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/allergy/{{Org_id}}",
            "use": "official",
            "value": "98457729"
        }
    ],
    "clinicalStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
                "code": "resolved",
                "display": "resolved"
            }
        ]
    },
    "verificationStatus": {
        "coding": [
            {
                "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification",
                "code": "confirmed",
                "display": "Confirmed"
            }
        ]
    },
    "category": [
        "food"
    ],
    "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "89811004",
                "display": "Gluten"
            }
        ],
        "text": "Alergi bahan gluten, khususnya ketika makan roti gandum"
    },
    "patient": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022"
    },
    "recordedDate": "2022-06-14T15:37:31+07:00",
    "recorder": {
        "reference": "Practitioner/N10000001"
    }
}

### AllergyIntolerance - PATCH
PATCH http://localhost:3000/api/satusehat/AllergyIntolerance/:id
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/category/0",
        "value": "medication"
    }
]

