
### AppointmentResponse - approved
POST {{base_url}}/AppointmentResponse
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "AppointmentResponse",
    "appointment": {
        "reference": "Appointment/0e0f2ff3-cf5c-48d8-9db2-b0f710fe514a"
    },
    "actor": {
        "reference": "HealthcareService/8cfb2d6f-dc20-4068-9113-805d426a6f17",
        "display": "Poliklinik Bedah Rawat Jalan Terpadu"
    },
    "participantStatus": "accepted",
    "comment": "A-12"
}

### AppointmentResponse - search by ID
GET {{base_url}}/AppointmentResponse/:id
Authorization: Bearer {{token}}

### AppointmentResponse - search by appointment
GET {{base_url}}/AppointmentResponse?appointment=0e0f2ff3-cf5c-48d8-9db2-b0f710fe514a
Authorization: Bearer {{token}}

### AppointmentResponse - PUT
PUT {{base_url}}/AppointmentResponse/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "AppointmentResponse",
    "id": "96bbe117-1738-4e93-abd7-23178dad38d3",
    "appointment": {
        "reference": "Appointment/0e0f2ff3-cf5c-48d8-9db2-b0f710fe514a"
    },
    "actor": {
        "reference": "HealthcareService/8cfb2d6f-dc20-4068-9113-805d426a6f17",
        "display": "Poliklinik Bedah Rawat Jalan Terpadu"
    },
    "participantStatus": "declined",
    "comment": "A-14"
}

### AppointmentResponse - PATCH
PATCH {{base_url}}/AppointmentResponse/:id
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/comment",
        "value": "A-123"
    }
]

