
### Organization - Create
POST http://localhost:3000/api/satusehat/Organization
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Organization",
    "active": true,
    "identifier": [
        {
            "use": "official",
            "system": "http://sys-ids.kemkes.go.id/organization/1000079374",
            "value": "Pos Imunisasi LUBUK BATANG"
        }
    ],
    "type": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                    "code": "dept",
                    "display": "Hospital Department"
                }
            ]
        }
    ],
    "name": "Pos Imunisasi",
    "telecom": [
        {
            "system": "phone",
            "value": "+6221-783042654",
            "use": "work"
        },
        {
            "system": "email",
            "value": "rs-satusehat@gmail.com",
            "use": "work"
        },
        {
            "system": "url",
            "value": "www.rs-satusehat@gmail.com",
            "use": "work"
        }
    ],
    "address": [
        {
            "use": "work",
            "type": "both",
            "line": [
                "Jalan Jati Asih"
            ],
            "city": "Jakarta",
            "postalCode": "55292",
            "country": "ID",
            "extension": [
                {
                    "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/administrativeCode",
                    "extension": [
                        {
                            "url": "province",
                            "valueCode": "31"
                        },
                        {
                            "url": "city",
                            "valueCode": "3171"
                        },
                        {
                            "url": "district",
                            "valueCode": "317101"
                        },
                        {
                            "url": "village",
                            "valueCode": "31710101"
                        }
                    ]
                }
            ]
        }
    ],
    "partOf": {
        "reference": "Organization/{{Org_id}}"
    }
}

### Organization - By ID
GET http://localhost:3000/api/satusehat/Organization/:id
Authorization: Bearer {{token}}

### Organization - Update
GET http://localhost:3000/api/satusehat/Organization/:id
Authorization: Bearer {{token}}

### Organization - Search by Name
GET http://localhost:3000/api/satusehat/Organization?name=paramarta
Authorization: Bearer {{token}}

### Organization - Search by PartOf
GET http://localhost:3000/api/satusehat/Organization?partof={{Org_id}}
Authorization: Bearer {{token}}

### Organization - Update
PUT http://localhost:3000/api/satusehat/Organization/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Organization",
    "id": "abddd50b-b22f-4d68-a1c3-d2c29a27698b",
    "active": false,
    "identifier": [
        {
            "use": "official",
            "system": "http://sys-ids.kemkes.go.id/organization/{{Org_id}}",
            "value": "R220001"
        }
    ],
    "type": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                    "code": "dept",
                    "display": "Hospital Department"
                }
            ]
        }
    ],
    "name": "Rawat Jalan Terpadu",
    "telecom": [
        {
            "system": "phone",
            "value": "+6221-783042654",
            "use": "work"
        },
        {
            "system": "email",
            "value": "rs-satusehat@gmail.com",
            "use": "work"
        },
        {
            "system": "url",
            "value": "www.rs-satusehat@gmail.com",
            "use": "work"
        }
    ],
    "address": [
        {
            "use": "work",
            "type": "both",
            "line": [
                "Jalan Jati Asih"
            ],
            "city": "Jakarta",
            "postalCode": "55292",
            "country": "ID",
            "extension": [
                {
                    "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/administrativeCode",
                    "extension": [
                        {
                            "url": "province",
                            "valueCode": "31"
                        },
                        {
                            "url": "city",
                            "valueCode": "3171"
                        },
                        {
                            "url": "district",
                            "valueCode": "317101"
                        },
                        {
                            "url": "village",
                            "valueCode": "31710101"
                        }
                    ]
                }
            ]
        }
    ],
    "partOf": {
        "reference": "Organization/{{Org_id}}"
    }
}

### Organization - Patch
PATCH http://localhost:3000/api/satusehat/Organization/:id
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/name",
        "value": "RAJAL TERPADU"
    }
]

