
### Practitioner - Search NIK
GET http://localhost:3000/api/satusehat/Practitioner?identifier=https://fhir.kemkes.go.id/id/nik|367400001111222
Authorization: Bearer {{token}}

### Practitioner - Search Name, Gender, Birthdate
GET http://localhost:3000/api/satusehat/Practitioner?name=Voigt&gender=male&birthdate=1945
Authorization: Bearer {{token}}

### Practitioner - By ID
GET http://localhost:3000/api/satusehat/Practitioner/:id
Authorization: Bearer {{token}}

