@Encounter_uuid=

### Procedure - Create
POST {{base_url}}/Procedure
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Procedure",
    "status": "completed",
    "category": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "103693007",
                "display": "Diagnostic procedure"
            }
        ],
        "text": "Diagnostic procedure"
    },
    "code": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/sid/icd-9-cm",
                "code": "87.44",
                "display": "Routine chest x-ray, so described"
            }
        ]
    },
    "subject": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Tindakan Rontgen Dada Budi Santoso pada Selasa tanggal 14 Juni 2022"
    },
    "performedPeriod": {
        "start": "2022-06-14T13:31:00+01:00",
        "end": "2022-06-14T14:27:00+01:00"
    },
    "performer": [
        {
            "actor": {
                "reference": "Practitioner/N10000001",
                "display": "Dokter Bronsig"
            }
        }
    ],
    "reasonCode": [
        {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10",
                    "code": "A15.0",
                    "display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture"
                }
            ]
        }
    ],
    "bodySite": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "302551006",
                    "display": "Entire Thorax"
                }
            ]
        }
    ],
    "note": [
        {
            "text": "Rontgen thorax melihat perluasan infiltrat dan kavitas."
        }
    ]
}

### Procedure - Search by Subject
GET {{base_url}}/Procedure?subject=100000030009
Authorization: Bearer {{token}}

### Procedure - Search by Subject and Encounter
GET {{base_url}}/Procedure?subject=100000030009&encounter={{Encounter_uuid}}
Authorization: Bearer {{token}}

### Procedure - Search by Encounter
GET {{base_url}}/Procedure?encounter={{Encounter_uuid}}
Authorization: Bearer {{token}}

### Procedure - By ID
GET {{base_url}}/Procedure/:id
Authorization: Bearer {{token}}

### Procedure - Update
PUT {{base_url}}/Procedure/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Procedure",
    "id": "87859868-c35b-4f7b-86dd-da9830ae58c5",
    "status": "completed",
    "category": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "103693007",
                "display": "Diagnostic procedure"
            }
        ],
        "text": "Diagnostic procedure"
    },
    "code": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/sid/icd-9-cm",
                "code": "87.44",
                "display": "Routine chest x-ray, so described"
            }
        ]
    },
    "subject": {
        "reference": "Patient/P00030004",
        "display": "Budi Santoso"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Tindakan Rontgen Dada Budi Santoso pada Selasa tanggal 14 Juni 2022"
    },
    "performedPeriod": {
        "start": "2022-06-14T13:31:00+01:00",
        "end": "2022-06-14T14:27:00+01:00"
    },
    "performer": [
        {
            "actor": {
                "reference": "Practitioner/N10000001",
                "display": "Dokter Bronsig"
            }
        }
    ],
    "reasonCode": [
        {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10",
                    "code": "A15.0",
                    "display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture"
                }
            ]
        }
    ],
    "bodySite": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "302551006",
                    "display": "Entire Thorax"
                }
            ]
        }
    ],
    "note": [
        {
            "text": "Rontgen thorax melihat perluasan infiltrat dan kavitas."
        }
    ]
}

### Procedure - PATCH
PATCH {{base_url}}/Procedure/:id
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/category/text",
        "value": "Surgical procedure"
    }
]

