
### Specimen - Create (Non Rujukan)
POST {{base_url}}/Specimen
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Specimen",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/specimen/{{Org_id}}",
            "value": "00001",
            "assigner": {
                "reference": "Organization/{{Org_id}}"
            }
        }
    ],
    "status": "available",
    "type": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "119294007",
                "display": "Dried blood specimen"
            }
        ]
    },
    "collection": {
        "collectedDateTime": "2022-06-14T08:15:00+07:00",
        "extension": [
            {
                "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/CollectorOrganization",
                "valueReference": {
                    "reference": "Organization/{{Org_id}}"
                }
            }
        ]
    },
    "subject": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "request": [
        {
            "reference": "ServiceRequest/61419a9c-51f9-4491-a6d0-e40e7c0eb7ab"
        }
    ],
    "receivedTime": "2022-06-14T08:25:00+07:00",
    "extension": [
        {
            "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/TransportedTime",
            "valueDateTime": "2022-06-14T08:23:00+07:00"
        }
    ]
}

### Specimen - Rujukan Sampel (with ReceivedTime & CollectorOrganization)
PUT {{base_url}}/Specimen/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Specimen",
    "id": "dbee2404-e11d-421f-8399-57cee518e0c7",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/specimen/{{Org_id}}",
            "value": "00001",
            "assigner": {
                "reference": "Organization/{{Org_id}}"
            }
        }
    ],
    "status": "available",
    "type": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "119294007",
                "display": "Dried blood specimen"
            }
        ]
    },
    "collection": {
        "collectedDateTime": "2022-06-14T08:15:00+07:00",
        "extension": [
            {
                "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/CollectorOrganization",
                "valueReference": {
                    "reference": "Organization/{{Org_id}}"
                }
            }
        ]
    },
    "subject": {
        "reference": "Patient/100000030004",
        "display": "Budi Santoso"
    },
    "request": [
        {
            "reference": "ServiceRequest/61419a9c-51f9-4491-a6d0-e40e7c0eb7ab"
        }
    ],
    "receivedTime": "2022-06-14T08:25:00+07:00",
    "extension": [
        {
            "url": "https://fhir.kemkes.go.id/r4/StructureDefinition/TransportedTime",
            "valueDateTime": "2022-06-14T08:23:00+07:00"
        }
    ]
}

### Specimen - By ID
GET {{base_url}}/Specimen/:id
Authorization: Bearer {{token}}

### Specimen - Search by Subject
GET {{base_url}}/Specimen?subject=100000030009
Authorization: Bearer {{token}}

### Specimen - Search by Request
GET {{base_url}}/Specimen?request=65b8a884-7a79-41e1-96ab-3fc30837ac66
Authorization: Bearer {{token}}

### Specimen - Search by Subject & Collector
GET {{base_url}}/Specimen?subject=100000030009&collector=1001194237
Authorization: Bearer {{token}}

### Specimen - Search by Subject & Date Collected
GET {{base_url}}/Specimen?subject=100000030009&collected=2022-06-28
Authorization: Bearer {{token}}

### Specimen - Search by Identifier Accession Number (Rujukan)
GET {{base_url}}/Specimen?identifier=http://sys-ids.kemkes.go.id/specimen-acsn|1000000004&request=3e8459cc-a9b1-405a-9e20-abfb5e40f8c7
Authorization: Bearer {{token}}

### Specimen - Update
PUT {{base_url}}/Specimen/:id
Authorization: Bearer {{token}}
Content-type: application/json

{
    "resourceType": "Specimen",
    "id": "cb2adef7-3971-4239-9cc2-6ae9981fe57d",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/specimen/{{Org_id}}",
            "value": "00001",
            "assigner": {
                "reference": "Organization/{{Org_id}}"
            }
        }
    ],
    "status": "unsatisfactory",
    "type": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "119297000",
                "display": "Blood specimen"
            }
        ]
    },
    "collection": {
        "method": {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "82078001",
                    "display": "Collection of blood specimen for laboratory"
                }
            ]
        },
        "collectedDateTime": "2022-06-14T08:15:00+07:00"
    },
    "subject": {
        "reference": "Patient/100000030009",
        "display": "Budi Santoso"
    },
    "request": [
        {
            "reference": "ServiceRequest/65b8a884-7a79-41e1-96ab-3fc30837ac66"
        }
    ],
    "receivedTime": "2022-06-14T08:25:00+07:00"
}

### Specimen - PATCH
PATCH {{base_url}}/Specimen/:id
Content-Type: application/json-patch+json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/status",
        "value": "unavailable"
    }
]

