### Menambahkan Alamat Baru
POST http://localhost:3000/api/master/address
Content-Type: application/json

{
    "use": "work",
    "line": "Jl. Raya Saimbang No.10, Sidoarjo",
    "city": "Sidoarjo",
    "postalCode": "61258",
    "country": "ID",
    "administrativeCode": "3515142002"
}

### Mendapatkan Daftar Alamat
GET http://localhost:3000/api/master/address

### Memperbarui Alamat yang Ada
PATCH http://localhost:3000/api/master/address
Content-Type: application/json

{
    "use": "work",
    "line": "Jl. Raya Saimbang No.10, Sidoarjo",
    "city": "Sidoarjo",
    "postalCode": "61258",
    "country": "ID",
    "administrativeCode": "3515142002"
}

### Menghapus Alamat Berdasarkan Penggunaan
DELETE http://localhost:3000/api/master/address?use=work
