### Menambahkan Informasi Telekomunikasi Baru
POST http://localhost:3000/api/master/telecom
Content-Type: application/json

{
    "system": "email",
    "use": "work",
    "value": "rahmanrahimrs@gmail.com"
}

### Mendapatkan Daftar Informasi Telekomunikasi
GET http://localhost:3000/api/master/telecom

### Memperbarui Informasi Telekomunikasi yang Ada
PATCH http://localhost:3000/api/master/telecom
Content-Type: application/json

{
    "system": "phone",
    "value": "+6231-8830010",
    "use": "work"
}

### Menghapus Informasi Telekomunikasi Berdasarkan Sistem dan Nilai
DELETE http://localhost:3000/api/master/telecom?system=website&value=rsrahmanrahim.org
