@Org_id=
@Encounter_uuid=

### ClinicalImpression - Create
POST http://localhost:3000/api/satusehat/ClinicalImpression
Content-type: application/json

{
    "resourceType": "ClinicalImpression",
    "identifier.0.system": "http://sys-ids.kemkes.go.id/clinicalimpression/{{Org_id}}",
    "identifier.0.use": "official",
    "identifier.0.value": "Prognosis_000123",
    "status": "completed",
    "description": "Bapak Budi Santoso terdiagnosa TB, dan tidak menunjukkan adanya resistensi obat",
    "subject.reference": "Patient/100000030009",
    "subject.display": "Budi Santoso",
    "encounter.reference": "Encounter/{{Encounter_uuid}}",
    "encounter.display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022",
    "effectiveDateTime": "2022-06-14T15:37:31+07:00",
    "date": "2022-06-14T15:15:31+07:00",
    "assessor.reference": "Practitioner/N10000001",
    "problem.0.reference": "Condition/f2bc12fe-0ab2-4e5c-a3cd-32c66150cbe9",
    "investigation.0.code.text": "Pemeriksaan Sputum BTA",
    "investigation.0.item.0.reference": "DiagnosticReport/a0fa6244-7638-43ba-bbc2-2af954761540",
    "investigation.0.item.1.reference": "Observation/56819f05-28b9-43c2-b0d1-3785768aa886",
    "summary": "Prognosis terhadap gejala klinis dan terkonfirmasi Tuberculosis",
    "finding.0.itemCodeableConcept.coding.0.system": "http://hl7.org/fhir/sid/icd-10",
    "finding.0.itemCodeableConcept.coding.0.code": "A15.0",
    "finding.0.itemCodeableConcept.coding.0.display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture",
    "finding.0.itemReference.reference": "Condition/f2bc12fe-0ab2-4e5c-a3cd-32c66150cbe9",
    "prognosisCodeableConcept.0.coding.0.system": "http://snomed.info/sct",
    "prognosisCodeableConcept.0.coding.0.code": "170968001",
    "prognosisCodeableConcept.0.coding.0.display": "Prognosis good"
}

### ClinicalImpression- Search by Subject with/without Encounter
GET http://localhost:3000/api/satusehat/ClinicalImpression?subject=100000030009&encounter={{Encounter_uuid}}

### ClinicalImpression - Search by ID
GET http://localhost:3000/api/satusehat/ClinicalImpression/:id

### ClinicalImpression - Update
PUT http://localhost:3000/api/satusehat/ClinicalImpression/:id
Content-type: application/json

{
    "resourceType": "ClinicalImpression",
    "id": "8163695a-6224-401e-9a78-7dbc9bed69af",
    "identifier.0.system": "http://sys-ids.kemkes.go.id/clinicalimpression/{{Org_id}}",
    "identifier.0.use": "official",
    "identifier.0.value": "Prognosis_000123",
    "status": "completed",
    "description": "Bapak Budi Santoso terdiagnosa TB, dan tidak menunjukkan adanya resistensi obat",
    "subject.reference": "Patient/100000030009",
    "subject.display": "Budi Santoso",
    "encounter.reference": "Encounter/{{Encounter_uuid}}",
    "encounter.display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022",
    "effectiveDateTime": "2022-06-14T15:37:31+07:00",
    "date": "2022-06-14T15:15:31+07:00",
    "assessor.reference": "Practitioner/N10000001",
    "problem.0.reference": "Condition/f2bc12fe-0ab2-4e5c-a3cd-32c66150cbe9",
    "investigation.0.code.text": "Pemeriksaan Sputum BTA",
    "investigation.0.item.0.reference": "DiagnosticReport/a0fa6244-7638-43ba-bbc2-2af954761540",
    "investigation.0.item.1.reference": "Observation/56819f05-28b9-43c2-b0d1-3785768aa886",
    "summary": "Prognosis terhadap gejala klinis dan terkonfirmasi Tuberculosis",
    "finding.0.itemCodeableConcept.coding.0.system": "http://hl7.org/fhir/sid/icd-10",
    "finding.0.itemCodeableConcept.coding.0.code": "A15.0",
    "finding.0.itemCodeableConcept.coding.0.display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture",
    "finding.0.itemReference.reference": "Condition/f2bc12fe-0ab2-4e5c-a3cd-32c66150cbe9",
    "prognosisCodeableConcept.0.coding.0.system": "http://snomed.info/sct",
    "prognosisCodeableConcept.0.coding.0.code": "65872000",
    "prognosisCodeableConcept.0.coding.0.display": "Fair prognosis"
}

### ClinicalImpression - PATCH
PATCH http://localhost:3000/api/satusehat/ClinicalImpression/:id
Content-Type: application/json-patch+json

{
    "0.op": "replace",
    "0.path": "/status",
    "0.value": "entered-in-error"
}

