@Org_id=

### ImagingStudy - POST (Single Image)
POST http://localhost:3000/api/satusehat/ImagingStudy
Content-type: application/json

{
    "resourceType": "ImagingStudy",
    "identifier.0.use": "usual",
    "identifier.0.type.coding.0.system": "http://terminology.hl7.org/CodeSystem/v2-0203",
    "identifier.0.type.coding.0.code": "ACSN",
    "identifier.0.system": "http://sys-ids.kemkes.go.id/acsn/{{Org_id}}",
    "identifier.0.value": "210610114146",
    "identifier.1.system": "urn:dicom:uid",
    "identifier.1.value": "urn:oid:2.16.380.31256.1.2449191199178232.20210610114926906",
    "status": "available",
    "modality.0.system": "http://dicom.nema.org/resources/ontology/DCM",
    "modality.0.code": "OP",
    "subject.reference": "Patient/100000030009",
    "started": "2021-06-10T11:41:46+07:00",
    "basedOn.0.reference": "ServiceRequest/83218f28-0027-4d3d-9981-94517f14223e",
    "numberOfSeries": 1,
    "numberOfInstances": 1,
    "series.0.uid": "2.16.380.31256.1.2449191199178232.20210610114926922.1",
    "series.0.number": 1,
    "series.0.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.0.modality.code": "OP",
    "series.0.numberOfInstances": 1,
    "series.0.started": "2021-06-10T11:45:01+07:00",
    "series.0.instance.0.uid": "2.16.380.31256.1.2449191199178232.20210610114930875.1.1",
    "series.0.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.77.1.5.1",
    "series.0.instance.0.number": 7,
    "series.0.instance.0.title": "ORIGINAL\\PRIMARY"
}

### ImagingStudy - Get ID based on Accession Number
GET http://localhost:3000/api/satusehat/ImagingStudy?identifier=http://sys-ids.kemkes.go.id/acsn/10000004|MR.221102.062

### ImagingStudy - PUT (Multiple Image)
PUT http://localhost:3000/api/satusehat/ImagingStudy/:id
Content-type: application/json

{
    "resourceType": "ImagingStudy",
    "id": "c4f3bfe3-91cd-40c4-b986-000c2150f051",
    "identifier.0.use": "usual",
    "identifier.0.type.coding.0.system": "http://terminology.hl7.org/CodeSystem/v2-0203",
    "identifier.0.type.coding.0.code": "ACSN",
    "identifier.0.system": "http://sys-ids.kemkes.go.id/acsn/{{Org_id}}",
    "identifier.0.value": "MR.221102.062",
    "identifier.1.system": "urn:dicom:uid",
    "identifier.1.value": "urn:oid:1.2.826.0.1.3680043.9.7307.1.20221102062",
    "status": "available",
    "modality.0.system": "http://dicom.nema.org/resources/ontology/DCM",
    "modality.0.code": "MR",
    "subject.reference": "Patient/100000030009",
    "started": "2022-11-02T13:37:38+07:00",
    "basedOn.0.reference": "ServiceRequest/cf498c0e-86e1-457e-b464-fe0ed8948da2",
    "numberOfSeries": 6,
    "numberOfInstances": 73,
    "description": "E018 - MRI Lumbosacral",
    "series.0.uid": "1.2.840.113619.2.388.14436926.9266122.15378.1667174756.530",
    "series.0.number": 7,
    "series.0.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.0.modality.code": "MR",
    "series.0.description": "Sag T1",
    "series.0.numberOfInstances": 12,
    "series.0.started": "2022-11-02T13:52:06+07:00",
    "series.0.instance.0.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.9",
    "series.0.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.0.number": 4,
    "series.0.instance.0.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.1.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.8",
    "series.0.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.1.number": 3,
    "series.0.instance.1.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.2.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.15",
    "series.0.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.2.number": 10,
    "series.0.instance.2.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.3.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.14",
    "series.0.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.3.number": 9,
    "series.0.instance.3.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.4.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.16",
    "series.0.instance.4.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.4.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.4.number": 11,
    "series.0.instance.4.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.5.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.17",
    "series.0.instance.5.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.5.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.5.number": 12,
    "series.0.instance.5.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.6.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.13",
    "series.0.instance.6.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.6.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.6.number": 8,
    "series.0.instance.6.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.7.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.12",
    "series.0.instance.7.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.7.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.7.number": 7,
    "series.0.instance.7.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.8.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.10",
    "series.0.instance.8.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.8.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.8.number": 5,
    "series.0.instance.8.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.9.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.11",
    "series.0.instance.9.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.9.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.9.number": 6,
    "series.0.instance.9.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.10.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.6",
    "series.0.instance.10.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.10.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.10.number": 1,
    "series.0.instance.10.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.0.instance.11.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.7",
    "series.0.instance.11.sopClass.system": "urn:ietf:rfc:3986",
    "series.0.instance.11.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.0.instance.11.number": 2,
    "series.0.instance.11.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.uid": "1.2.840.113619.2.388.14436926.9266122.15378.1667174756.531",
    "series.1.number": 8,
    "series.1.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.1.modality.code": "MR",
    "series.1.description": "Ax T2",
    "series.1.numberOfInstances": 15,
    "series.1.started": "2022-11-02T13:55:31+07:00",
    "series.1.instance.0.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.155",
    "series.1.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.0.number": 6,
    "series.1.instance.0.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.1.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.154",
    "series.1.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.1.number": 5,
    "series.1.instance.1.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.2.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.156",
    "series.1.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.2.number": 7,
    "series.1.instance.2.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.3.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.157",
    "series.1.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.3.number": 8,
    "series.1.instance.3.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.4.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.153",
    "series.1.instance.4.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.4.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.4.number": 4,
    "series.1.instance.4.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.5.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.152",
    "series.1.instance.5.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.5.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.5.number": 3,
    "series.1.instance.5.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.6.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.150",
    "series.1.instance.6.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.6.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.6.number": 1,
    "series.1.instance.6.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.7.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.151",
    "series.1.instance.7.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.7.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.7.number": 2,
    "series.1.instance.7.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.8.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.160",
    "series.1.instance.8.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.8.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.8.number": 11,
    "series.1.instance.8.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.9.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.161",
    "series.1.instance.9.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.9.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.9.number": 12,
    "series.1.instance.9.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.10.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.163",
    "series.1.instance.10.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.10.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.10.number": 14,
    "series.1.instance.10.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.11.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.162",
    "series.1.instance.11.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.11.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.11.number": 13,
    "series.1.instance.11.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.12.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.159",
    "series.1.instance.12.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.12.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.12.number": 10,
    "series.1.instance.12.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.13.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.164",
    "series.1.instance.13.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.13.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.13.number": 15,
    "series.1.instance.13.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.1.instance.14.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.158",
    "series.1.instance.14.sopClass.system": "urn:ietf:rfc:3986",
    "series.1.instance.14.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.1.instance.14.number": 9,
    "series.1.instance.14.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.uid": "1.2.840.113619.2.388.14436926.9266122.15378.1667174756.529",
    "series.2.number": 6,
    "series.2.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.2.modality.code": "MR",
    "series.2.description": "Sag T2",
    "series.2.numberOfInstances": 12,
    "series.2.started": "2022-11-02T13:47:41+07:00",
    "series.2.instance.0.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.868",
    "series.2.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.0.number": 7,
    "series.2.instance.0.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.1.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.869",
    "series.2.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.1.number": 8,
    "series.2.instance.1.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.2.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.867",
    "series.2.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.2.number": 6,
    "series.2.instance.2.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.3.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.873",
    "series.2.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.3.number": 12,
    "series.2.instance.3.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.4.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.872",
    "series.2.instance.4.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.4.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.4.number": 11,
    "series.2.instance.4.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.5.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.866",
    "series.2.instance.5.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.5.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.5.number": 5,
    "series.2.instance.5.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.6.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.870",
    "series.2.instance.6.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.6.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.6.number": 9,
    "series.2.instance.6.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.7.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.864",
    "series.2.instance.7.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.7.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.7.number": 3,
    "series.2.instance.7.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.8.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.865",
    "series.2.instance.8.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.8.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.8.number": 4,
    "series.2.instance.8.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.9.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.871",
    "series.2.instance.9.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.9.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.9.number": 10,
    "series.2.instance.9.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.10.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.862",
    "series.2.instance.10.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.10.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.10.number": 1,
    "series.2.instance.10.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.2.instance.11.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174787.863",
    "series.2.instance.11.sopClass.system": "urn:ietf:rfc:3986",
    "series.2.instance.11.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.2.instance.11.number": 2,
    "series.2.instance.11.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.3.uid": "1.2.840.113619.2.388.14436926.9266122.15378.1667174756.533",
    "series.3.number": 10,
    "series.3.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.3.modality.code": "MR",
    "series.3.description": "Myelo 2D",
    "series.3.numberOfInstances": 4,
    "series.3.started": "2022-11-02T14:01:54+07:00",
    "series.3.instance.0.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.446",
    "series.3.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.3.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.3.instance.0.number": 3,
    "series.3.instance.0.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.3.instance.1.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.447",
    "series.3.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.3.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.3.instance.1.number": 4,
    "series.3.instance.1.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.3.instance.2.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.445",
    "series.3.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.3.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.3.instance.2.number": 2,
    "series.3.instance.2.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.3.instance.3.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.444",
    "series.3.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.3.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.3.instance.3.number": 1,
    "series.3.instance.3.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.uid": "1.2.840.113619.2.388.14436926.9266122.15378.1667174756.532",
    "series.4.number": 9,
    "series.4.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.4.modality.code": "MR",
    "series.4.description": "Ax T1",
    "series.4.numberOfInstances": 15,
    "series.4.started": "2022-11-02T13:58:46+07:00",
    "series.4.instance.0.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.297",
    "series.4.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.0.number": 1,
    "series.4.instance.0.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.1.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.308",
    "series.4.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.1.number": 8,
    "series.4.instance.1.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.2.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.309",
    "series.4.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.2.number": 10,
    "series.4.instance.2.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.3.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.301",
    "series.4.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.3.number": 9,
    "series.4.instance.3.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.4.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.300",
    "series.4.instance.4.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.4.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.4.number": 7,
    "series.4.instance.4.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.5.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.302",
    "series.4.instance.5.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.5.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.5.number": 11,
    "series.4.instance.5.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.6.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.303",
    "series.4.instance.6.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.6.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.6.number": 13,
    "series.4.instance.6.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.7.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.298",
    "series.4.instance.7.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.7.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.7.number": 3,
    "series.4.instance.7.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.8.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.307",
    "series.4.instance.8.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.8.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.8.number": 6,
    "series.4.instance.8.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.9.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.306",
    "series.4.instance.9.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.9.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.9.number": 4,
    "series.4.instance.9.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.10.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.299",
    "series.4.instance.10.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.10.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.10.number": 5,
    "series.4.instance.10.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.11.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.310",
    "series.4.instance.11.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.11.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.11.number": 12,
    "series.4.instance.11.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.12.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.304",
    "series.4.instance.12.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.12.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.12.number": 15,
    "series.4.instance.12.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.13.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.305",
    "series.4.instance.13.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.13.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.13.number": 2,
    "series.4.instance.13.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.4.instance.14.uid": "1.2.840.113619.2.388.14436926.9266122.13603.1667174788.311",
    "series.4.instance.14.sopClass.system": "urn:ietf:rfc:3986",
    "series.4.instance.14.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.4.instance.14.number": 14,
    "series.4.instance.14.title": "ORIGINAL\\PRIMARY\\OTHER",
    "series.5.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646300.1",
    "series.5.number": 400,
    "series.5.modality.system": "http://dicom.nema.org/resources/ontology/DCM",
    "series.5.modality.code": "MR",
    "series.5.description": "Sag T2 Pasting",
    "series.5.numberOfInstances": 15,
    "series.5.started": "2022-11-02T14:04:06+07:00",
    "series.5.instance.0.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646363.2",
    "series.5.instance.0.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.0.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.0.number": 1,
    "series.5.instance.0.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.1.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646383.7",
    "series.5.instance.1.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.1.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.1.number": 6,
    "series.5.instance.1.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.2.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646381.6",
    "series.5.instance.2.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.2.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.2.number": 5,
    "series.5.instance.2.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.3.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646379.5",
    "series.5.instance.3.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.3.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.3.number": 4,
    "series.5.instance.3.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.4.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646393.12",
    "series.5.instance.4.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.4.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.4.number": 11,
    "series.5.instance.4.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.5.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646371.3",
    "series.5.instance.5.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.5.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.5.number": 2,
    "series.5.instance.5.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.6.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646377.4",
    "series.5.instance.6.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.6.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.6.number": 3,
    "series.5.instance.6.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.7.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646391.11",
    "series.5.instance.7.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.7.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.7.number": 10,
    "series.5.instance.7.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.8.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646395.13",
    "series.5.instance.8.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.8.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.8.number": 12,
    "series.5.instance.8.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.9.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646397.14",
    "series.5.instance.9.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.9.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.9.number": 13,
    "series.5.instance.9.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.10.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646401.16",
    "series.5.instance.10.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.10.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.10.number": 15,
    "series.5.instance.10.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.11.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646389.10",
    "series.5.instance.11.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.11.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.11.number": 9,
    "series.5.instance.11.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.12.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646399.15",
    "series.5.instance.12.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.12.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.12.number": 14,
    "series.5.instance.12.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.13.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646385.8",
    "series.5.instance.13.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.13.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.13.number": 7,
    "series.5.instance.13.title": "DERIVED\\SECONDARY\\PASTED",
    "series.5.instance.14.uid": "1.2.840.113619.2.233.242211435144138.452.1667372646387.9",
    "series.5.instance.14.sopClass.system": "urn:ietf:rfc:3986",
    "series.5.instance.14.sopClass.code": "urn:oid:1.2.840.10008.5.1.4.1.1.4",
    "series.5.instance.14.number": 8,
    "series.5.instance.14.title": "DERIVED\\SECONDARY\\PASTED"
}

