@Encounter_uuid=

### Observation - Create
POST http://localhost:3000/api/satusehat/Observation
Content-type: application/json

{
    "resourceType": "Observation",
    "status": "final",
    "category.0.coding.0.system": "http://terminology.hl7.org/CodeSystem/observation-category",
    "category.0.coding.0.code": "vital-signs",
    "category.0.coding.0.display": "Vital Signs",
    "code.coding.0.system": "http://loinc.org",
    "code.coding.0.code": "8867-4",
    "code.coding.0.display": "Heart rate",
    "subject.reference": "Patient/100000030009",
    "performer.0.reference": "Practitioner/N10000001",
    "encounter.reference": "Encounter/{{Encounter_uuid}}",
    "encounter.display": "Pemeriksaan Fisik Nadi Budi Santoso di hari Selasa, 14 Juni 2022",
    "effectiveDateTime": "2022-07-14",
    "issued": "2022-07-14T14:27:00+07:00",
    "valueQuantity.value": 80,
    "valueQuantity.unit": "beats/minute",
    "valueQuantity.system": "http://unitsofmeasure.org",
    "valueQuantity.code": "/min"
}

### Observation - Search by Subject
GET http://localhost:3000/api/satusehat/Observation?subject=100000030009

### Observation - Search by Subject and Encounter
GET http://localhost:3000/api/satusehat/Observation?subject=100000030009&encounter={{Encounter_uuid}}

### Observation - Search by Encounter
GET http://localhost:3000/api/satusehat/Observation?encounter={{Encounter_uuid}}

### Observation - Search by ServiceRequest BasedOn
GET http://localhost:3000/api/satusehat/Observation?based-on=124dfb1f-b817-47d6-82ab-7bfed09e8594&subject=100000030009

### Observation - By ID
GET http://localhost:3000/api/satusehat/Observation/:id

### Observation - Update
PUT http://localhost:3000/api/satusehat/Observation/:id
Content-type: application/json

{
    "resourceType": "Observation",
    "status": "final",
    "id": "40a8c3c0-89fb-4ed3-b646-399c6a909d8a",
    "category.0.coding.0.system": "http://terminology.hl7.org/CodeSystem/observation-category",
    "category.0.coding.0.code": "vital-signs",
    "category.0.coding.0.display": "Vital Signs",
    "code.coding.0.system": "http://loinc.org",
    "code.coding.0.code": "9279-1",
    "code.coding.0.display": "Respiratory rate",
    "subject.reference": "Patient/100000030009",
    "encounter.reference": "Encounter/{{Encounter_uuid}}",
    "encounter.display": "Pemeriksaan Fisik Pernafasan Budi Santoso di hari Selasa, 14 Juni 2022",
    "effectiveDateTime": "2022-07-14",
    "issued": "2022-07-14T14:27:00+07:00",
    "valueQuantity.value": 22,
    "valueQuantity.unit": "breaths/minute",
    "valueQuantity.system": "http://unitsofmeasure.org",
    "valueQuantity.code": "/min"
}

### Observation - PATCH
PATCH http://localhost:3000/api/satusehat/Observation/:id
Content-Type: application/json-patch+json

{
    "0.op": "replace",
    "0.path": "/valueQuantity/value",
    "0.value": 15
}

