
### Patient - Search NIK
GET http://localhost:3000/api/satusehat/Patient?identifier=https://fhir.kemkes.go.id/id/nik|9271060312000001

### Patient - Bayi Search NIK Ibu
GET http://localhost:3000/api/satusehat/Patient?identifier=https://fhir.kemkes.go.id/id/nik-ibu|367400001111222

### Patient - Search Name, Birtdate, NIK
GET http://localhost:3000/api/satusehat/Patient?name=patient&birthdate=1980-12-03&identifier=https://fhir.kemkes.go.id/id/nik|9271060312000001

### Patient - Search Name, Birthdate, Gender
GET http://localhost:3000/api/satusehat/Patient?name=patient 1&birthdate=1980-12-03&gender=male

### Patient - By ID
GET http://localhost:3000/api/satusehat/Patient/:id

### Patient - Create by NIK
POST http://localhost:3000/api/satusehat/Patient
Content-type: application/json

{
    "resourceType": "Patient",
    "meta.profile.0": "https://fhir.kemkes.go.id/r4/StructureDefinition/Patient",
    "identifier.0.use": "official",
    "identifier.0.system": "https://fhir.kemkes.go.id/id/nik",
    "identifier.0.value": "3174031002890009",
    "identifier.1.use": "official",
    "identifier.1.system": "https://fhir.kemkes.go.id/id/paspor",
    "identifier.1.value": "A01111222",
    "identifier.2.use": "official",
    "identifier.2.system": "https://fhir.kemkes.go.id/id/kk",
    "identifier.2.value": "367400001111111",
    "active": true,
    "name.0.use": "official",
    "name.0.text": "John Smith",
    "gender": "female",
    "birthDate": "1945-11-17",
    "deceasedBoolean": false,
    "maritalStatus.coding.0.system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
    "maritalStatus.coding.0.code": "M",
    "maritalStatus.coding.0.display": "Married",
    "maritalStatus.text": "Married",
    "multipleBirthInteger": 0,
    "contact.0.relationship.0.coding.0.system": "http://terminology.hl7.org/CodeSystem/v2-0131",
    "contact.0.relationship.0.coding.0.code": "C",
    "contact.0.name.use": "official",
    "contact.0.name.text": "Jane Smith",
    "contact.0.telecom.0.system": "phone",
    "contact.0.telecom.0.value": "0690383372",
    "contact.0.telecom.0.use": "mobile",
    "communication.0.language.coding.0.system": "urn:ietf:bcp:47",
    "communication.0.language.coding.0.code": "id-ID",
    "communication.0.language.coding.0.display": "Indonesian",
    "communication.0.language.text": "Indonesian",
    "communication.0.preferred": true,
    "extension.0.url": "https://fhir.kemkes.go.id/r4/StructureDefinition/birthPlace",
    "extension.0.valueAddress.city": "Bandung",
    "extension.0.valueAddress.country": "ID",
    "extension.1.url": "https://fhir.kemkes.go.id/r4/StructureDefinition/citizenshipStatus",
    "extension.1.valueCode": "WNI"
}

### Patient - Create by Mother's NIK (Newborn)
POST http://localhost:3000/api/satusehat/Patient
Content-type: application/json

{
    "resourceType": "Patient",
    "meta.profile.0": "https://fhir.kemkes.go.id/r4/StructureDefinition/Patient",
    "identifier.0.use": "official",
    "identifier.0.system": "https://fhir.kemkes.go.id/id/nik-ibu",
    "identifier.0.value": "360328xxxxxxx",
    "active": true,
    "name.0.use": "official",
    "name.0.text": "John Smith",
    "gender": "female",
    "birthDate": "1920-02-28",
    "deceasedBoolean": false,
    "maritalStatus.coding.0.system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
    "maritalStatus.coding.0.code": "M",
    "maritalStatus.coding.0.display": "Married",
    "maritalStatus.text": "Married",
    "multipleBirthInteger": 0,
    "contact.0.relationship.0.coding.0.system": "http://terminology.hl7.org/CodeSystem/v2-0131",
    "contact.0.relationship.0.coding.0.code": "C",
    "contact.0.name.use": "official",
    "contact.0.name.text": "Jane Smith",
    "contact.0.telecom.0.system": "phone",
    "contact.0.telecom.0.value": "0690383372",
    "contact.0.telecom.0.use": "mobile",
    "communication.0.language.coding.0.system": "urn:ietf:bcp:47",
    "communication.0.language.coding.0.code": "id-ID",
    "communication.0.language.coding.0.display": "Indonesian",
    "communication.0.language.text": "Indonesian",
    "communication.0.preferred": true,
    "extension.0.url": "https://fhir.kemkes.go.id/r4/StructureDefinition/birthPlace",
    "extension.0.valueAddress.city": "Bandung",
    "extension.0.valueAddress.country": "ID",
    "extension.1.url": "https://fhir.kemkes.go.id/r4/StructureDefinition/citizenshipStatus",
    "extension.1.valueCode": "WNI"
}

