@Org_id=

### HealthcareService - Buat Poli
POST http://localhost:3000/api/satusehat/HealthcareService
Content-type: application/json

{
    "resourceType": "HealthcareService",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/healthcareservice/{{Org_id}}",
            "value": "HS-19920029"
        }
    ],
    "active": true,
    "providedBy": {
        "reference": "Organization/{{Org_id}}"
    },
    "type": [
        {
            "coding": [
                {
                    "system": "http://sys-ids.kemkes.go.id/bpjs-poli",
                    "code": "JAN",
                    "display": "Poli Jantung"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/service-type",
                    "code": "305",
                    "display": "Counselling"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/service-type",
                    "code": "221",
                    "display": "Surgery - General"
                }
            ]
        }
    ],
    "specialty": [
        {
            "coding": [
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/clinical-speciality",
                    "code": "S001.09",
                    "display": "Penyakit dalam kardiovaskular "
                }
            ]
        }
    ],
    "location": [
        {
            "reference": "Location/b017aa54-f1df-4ec2-9d84-8823815d7228",
            "display": "Ruang 1A, Poliklinik Bedah Rawat Jalan Terpadu, Lantai 2, Gedung G"
        }
    ],
    "name": "Poliklinik Bedah Rawat Jalan Terpadu",
    "program": [
        {
            "coding": [
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/program",
                    "code": "1000200",
                    "display": "Program JKN"
                }
            ]
        }
    ]
}

### HealthcareService - GET by ID
GET http://localhost:3000/api/satusehat/HealthcareService/:id

### HealthcareService - GET by specialty
GET http://localhost:3000/api/satusehat/HealthcareService?specialty=S001.09

### HealthcareService - PUT
PUT http://localhost:3000/api/satusehat/HealthcareService/:id
Content-type: application/json

{
    "resourceType": "HealthcareService",
    "id": "8cfb2d6f-dc20-4068-9113-805d426a6f17",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/healthcareservice/{{Org_id}}",
            "value": "HS-19920029_123"
        }
    ],
    "active": true,
    "providedBy": {
        "reference": "Organization/{{Org_id}}"
    },
    "type": [
        {
            "coding": [
                {
                    "system": "http://sys-ids.kemkes.go.id/bpjs-poli",
                    "code": "JAN",
                    "display": "Poli Jantung"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/service-type",
                    "code": "305",
                    "display": "Counselling"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/service-type",
                    "code": "221",
                    "display": "Surgery - General"
                }
            ]
        }
    ],
    "specialty": [
        {
            "coding": [
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/clinical-speciality",
                    "code": "S001.09",
                    "display": "Penyakit dalam kardiovaskular "
                }
            ]
        }
    ],
    "location": [
        {
            "reference": "Location/b017aa54-f1df-4ec2-9d84-8823815d7228",
            "display": "Ruang 1A, Poliklinik Bedah Rawat Jalan Terpadu, Lantai 2, Gedung G"
        }
    ],
    "name": "Poliklinik Bedah Rawat Jalan Terpadu",
    "program": [
        {
            "coding": [
                {
                    "system": "http://terminology.kemkes.go.id/CodeSystem/program",
                    "code": "1000200",
                    "display": "Program JKN"
                }
            ]
        }
    ]
}

### HealthcareService - PATCH
PATCH http://localhost:3000/api/satusehat/HealthcareService/:id
Content-Type: application/json-patch+json

[
    {
        "op": "replace",
        "path": "/name",
        "value": "Poliklinik Jantung Konsultan Bedah Thorax Kardiovaskular"
    }
]

