@Org_id=
@Encounter_uuid=

### ServiceRequest - Laboratorium Non Rujukan Eksternal
POST http://localhost:3000/api/satusehat/ServiceRequest
Content-type: application/json

{
    "resourceType": "ServiceRequest",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/servicerequest/{{Org_id}}",
            "value": "00001"
        }
    ],
    "status": "active",
    "intent": "original-order",
    "priority": "routine",
    "category": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "108252007",
                    "display": "Laboratory procedure"
                }
            ]
        }
    ],
    "code": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "11477-7",
                "display": "Microscopic observation [Identifier] in Sputum by Acid fast stain"
            }
        ],
        "text": "Pemeriksaan Sputum BTA"
    },
    "subject": {
        "reference": "Patient/100000030009"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Permintaan BTA Sputum Budi Santoso di hari Selasa, 14 Juni 2022 pukul 09:30 WIB"
    },
    "occurrenceDateTime": "2022-06-14T09:30:27+07:00",
    "authoredOn": "2022-06-13T12:30:27+07:00",
    "requester": {
        "reference": "Practitioner/N10000001",
        "display": "Dokter Bronsig"
    },
    "performer": [
        {
            "reference": "Practitioner/N10000005",
            "display": "Fatma"
        }
    ],
    "reasonCode": [
        {
            "text": "Periksa jika ada kemungkinan Tuberculosis"
        }
    ]
}

### ServiceRequest - Rujukan/Kontrol Internal (Faskes sama)
POST http://localhost:3000/api/satusehat/ServiceRequest
Content-type: application/json

{
    "resourceType": "ServiceRequest",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/servicerequest/{{Org_id}}",
            "value": "00001"
        }
    ],
    "status": "active",
    "intent": "original-order",
    "priority": "routine",
    "category": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "306098008",
                    "display": "Self-referral"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "11429006",
                    "display": "Consultation"
                }
            ]
        }
    ],
    "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "185389009",
                "display": "Follow-up visit"
            }
        ],
        "text": "Kontrol rutin regimen TB bulan ke-2"
    },
    "subject": {
        "reference": "Patient/100000030009"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022"
    },
    "occurrenceDateTime": "2022-07-14",
    "authoredOn": "2022-06-14T09:30:27+07:00",
    "requester": {
        "reference": "Practitioner/N10000001",
        "display": "Dokter Bronsig"
    },
    "performer": [
        {
            "reference": "Practitioner/N10000005",
            "display": "Fatma"
        }
    ],
    "reasonCode": [
        {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10",
                    "code": "A15.0",
                    "display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture"
                }
            ],
            "text": "Kontrol rutin bulanan"
        }
    ],
    "locationCode": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
                    "code": "OF",
                    "display": "Outpatient Facility"
                }
            ]
        }
    ],
    "locationReference": [
        {
            "reference": "Location/ef011065-38c9-46f8-9c35-d1fe68966a3e",
            "display": "Ruang 1A, Poliklinik Rawat Jalan"
        }
    ],
    "patientInstruction": "Kontrol setelah 1 bulan minum obat anti tuberkulosis. Dalam keadaan darurat dapat menghubungi hotline RS di nomor 14045"
}

### ServiceRequest - Rujukan Radiologi Eksternal
POST http://localhost:3000/api/satusehat/ServiceRequest
Content-type: application/json

{
    "resourceType": "ServiceRequest",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/servicerequest/{{Org_id}}",
            "value": "00001"
        }
    ],
    "status": "active",
    "intent": "original-order",
    "priority": "routine",
    "category": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "3457005",
                    "display": "Patient referral"
                }
            ]
        },
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "363679005",
                    "display": "Imaging"
                }
            ]
        }
    ],
    "code": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "79103-8",
                "display": "CT Abdomen W contrast IV"
            }
        ],
        "text": "Pemeriksaan CT Scan Abdomen Atas"
    },
    "subject": {
        "reference": "Patient/100000030009"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Kunjungan Budi Santoso di hari Selasa, 14 Juni 2022"
    },
    "occurrenceDateTime": "2022-07-14",
    "authoredOn": "2022-06-14T09:30:27+07:00",
    "requester": {
        "reference": "Practitioner/N10000001",
        "display": "Dokter Bronsig"
    },
    "performer": [
        {
            "reference": "Practitioner/N10000005",
            "display": "Fatma"
        }
    ],
    "reasonCode": [
        {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/sid/icd-10",
                    "code": "A15.0",
                    "display": "Tuberculosis of lung, confirmed by sputum microscopy with or without culture"
                }
            ],
            "text": "Kontrol rutin bulanan"
        }
    ],
    "locationCode": [
        {
            "coding": [
                {
                    "system": "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
                    "code": "OF",
                    "display": "Outpatient Facility"
                }
            ]
        }
    ],
    "locationReference": [
        {
            "reference": "Location/ef011065-38c9-46f8-9c35-d1fe68966a3e",
            "display": "Ruang 1A, Poliklinik Rawat Jalan"
        }
    ],
    "patientInstruction": "Kontrol setelah 1 bulan minum obat anti tuberkulosis. Dalam keadaan darurat dapat menghubungi hotline RS di nomor 14045"
}

### ServiceRequest - Search by Identifier
GET http://localhost:3000/api/satusehat/ServiceRequest?identifier=http://sys-ids.kemkes.go.id/acsn/{{Org_id}}|21120054

### ServiceRequest - Search by Subject
GET http://localhost:3000/api/satusehat/ServiceRequest?subject=100000030009

### ServiceRequest - Search by Subject and Encounter
GET http://localhost:3000/api/satusehat/ServiceRequest?subject=100000030009&encounter={{Encounter_uuid}}

### ServiceRequest - Search by Encounter
GET http://localhost:3000/api/satusehat/ServiceRequest?encounter={{Encounter_uuid}}

### ServiceRequest - By ID
GET http://localhost:3000/api/satusehat/ServiceRequest/:id

### ServiceRequest - Search by Nomor Rujukan Nasional
GET http://localhost:3000/api/satusehat/ServiceRequest?identifier=http://sys-ids.kemkes.go.id/referral-number|1000000005

### ServiceRequest - Update
PUT http://localhost:3000/api/satusehat/ServiceRequest/:id
Content-type: application/json

{
    "resourceType": "ServiceRequest",
    "id": "1204ee6c-4af3-4448-946c-f2f1c2bbc50a",
    "identifier": [
        {
            "system": "http://sys-ids.kemkes.go.id/servicerequest/{{Org_id}}",
            "value": "00001"
        }
    ],
    "status": "active",
    "intent": "original-order",
    "priority": "routine",
    "category": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "108252007",
                    "display": "Laboratory procedure"
                }
            ]
        }
    ],
    "code": {
        "coding": [
            {
                "system": "http://loinc.org",
                "code": "11477-7",
                "display": "Microscopic observation [Identifier] in Sputum by Acid fast stain"
            }
        ],
        "text": "Pemeriksaan Sputum BTA"
    },
    "subject": {
        "reference": "Patient/100000030009"
    },
    "encounter": {
        "reference": "Encounter/{{Encounter_uuid}}",
        "display": "Permintaan BTA Sputum Budi Santoso di hari Selasa, 14 Juni 2022 pukul 09:30 WIB"
    },
    "occurrenceDateTime": "2022-06-14T09:30:27+07:00",
    "authoredOn": "2022-06-13T12:30:27+07:00",
    "requester": {
        "reference": "Practitioner/N10000001",
        "display": "Dokter Bronsig"
    },
    "performer": [
        {
            "reference": "Practitioner/N10000005",
            "display": "Fatma"
        }
    ],
    "reasonCode": [
        {
            "text": "Periksa jika ada kemungkinan Tuberculosis"
        }
    ]
}

### ServiceRequest - PATCH
PATCH http://localhost:3000/api/satusehat/ServiceRequest/:id
Content-Type: application/json-patch+json

[
    {
        "op": "replace",
        "path": "/status",
        "value": "entered-in-error"
    }
]

